# -*- coding: utf-8 -*-
"""Code modifier (final) alien.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoD7B3rqKdtR6A8HVB4fYhO_FvMW4h3W
"""

#!/usr/bin/env python
import random
import os
import json
from typing import List
import pygame as pg

if not pg.image.get_extended():
    raise SystemExit("Sorry, extended image module required")

# -----------------------------
# CONSTANTES DU JEU
# -----------------------------
SCREENRECT = pg.Rect(0, 0, 640, 480)
MAX_SHOTS = 2
ALIEN_RELOAD = 12
SCORE = 0
LIVES = 3

main_dir = os.path.split(os.path.abspath(__file__))[0]
HIGH_SCORE_FILE = os.path.join(main_dir, "high_scores.json")

DIFFICULTIES = {
    "Facile": {
        "alien_speed": 8,
        "bomb_odds": 90,
        "alien_odds": 35,
        "max_aliens": 4,
    },
    "Moyen": {
        "alien_speed": 13,
        "bomb_odds": 60,
        "alien_odds": 22,
        "max_aliens": 6,
    },
    "Difficile": {
        "alien_speed": 18,
        "bomb_odds": 35,
        "alien_odds": 14,
        "max_aliens": 9,
    },
}

current_difficulty = "Moyen"


# -----------------------------
# CHARGEMENT DES RESSOURCES
# -----------------------------
def load_image(file):
    file = os.path.join(main_dir, "data", file)
    try:
        surface = pg.image.load(file)
    except pg.error:
        raise SystemExit(f'Could not load image "{file}" {pg.get_error()}')
    return surface.convert()


def load_sound(file):
    if not pg.mixer:
        return None
    file = os.path.join(main_dir, "data", file)
    try:
        return pg.mixer.Sound(file)
    except pg.error:
        print(f"Warning, unable to load {file}")
    return None


# -----------------------------
# MEILLEURS SCORES JSON
# -----------------------------
def load_high_scores():
    if not os.path.exists(HIGH_SCORE_FILE):
        return []

    try:
        with open(HIGH_SCORE_FILE, "r", encoding="utf-8") as file:
            scores = json.load(file)
            return scores
    except:
        return []


def save_high_score(score, difficulty):
    scores = load_high_scores()

    scores.append({
        "name": "Player",
        "score": score,
        "difficulty": difficulty
    })

    scores = sorted(scores, key=lambda x: x["score"], reverse=True)
    scores = scores[:5]

    with open(HIGH_SCORE_FILE, "w", encoding="utf-8") as file:
        json.dump(scores, file, indent=4)


# -----------------------------
# CLASSES DU JEU
# -----------------------------
class Player(pg.sprite.Sprite):
    speed = 10
    bounce = 24
    gun_offset = -11
    images: List[pg.Surface] = []

    def __init__(self, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.image = self.images[0]
        self.rect = self.image.get_rect(midbottom=SCREENRECT.midbottom)
        self.reloading = 0
        self.origtop = self.rect.top
        self.facing = -1
        self.shield = False
        self.double_shot = False

    def move(self, direction):
        if direction:
            self.facing = direction

        self.rect.move_ip(direction * self.speed, 0)
        self.rect = self.rect.clamp(SCREENRECT)

        if direction < 0:
            self.image = self.images[0]
        elif direction > 0:
            self.image = self.images[1]

        self.rect.top = self.origtop - (self.rect.left // self.bounce % 2)

    def gunpos(self):
        pos = self.facing * self.gun_offset + self.rect.centerx
        return pos, self.rect.top


class Alien(pg.sprite.Sprite):
    animcycle = 12
    images: List[pg.Surface] = []

    def __init__(self, speed, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.image = self.images[0]
        self.rect = self.image.get_rect()
        self.facing = random.choice((-1, 1)) * speed
        self.frame = 0

        if self.facing < 0:
            self.rect.right = SCREENRECT.right

    def update(self):
        self.rect.move_ip(self.facing, 0)

        if not SCREENRECT.contains(self.rect):
            self.facing = -self.facing
            self.rect.top = self.rect.bottom + 1
            self.rect = self.rect.clamp(SCREENRECT)

        self.frame += 1
        self.image = self.images[self.frame // self.animcycle % 3]


class Explosion(pg.sprite.Sprite):
    defaultlife = 12
    animcycle = 3
    images: List[pg.Surface] = []

    def __init__(self, actor, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.image = self.images[0]
        self.rect = self.image.get_rect(center=actor.rect.center)
        self.life = self.defaultlife

    def update(self):
        self.life -= 1
        self.image = self.images[self.life // self.animcycle % 2]

        if self.life <= 0:
            self.kill()


class Shot(pg.sprite.Sprite):
    speed = -11
    images: List[pg.Surface] = []

    def __init__(self, pos, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.image = self.images[0]
        self.rect = self.image.get_rect(midbottom=pos)

    def update(self):
        self.rect.move_ip(0, self.speed)

        if self.rect.top <= 0:
            self.kill()


class Bomb(pg.sprite.Sprite):
    speed = 9
    images: List[pg.Surface] = []

    def __init__(self, alien, explosion_group, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.image = self.images[0]
        self.rect = self.image.get_rect(midbottom=alien.rect.move(0, 5).midbottom)
        self.explosion_group = explosion_group

    def update(self):
        self.rect.move_ip(0, self.speed)

        if self.rect.bottom >= 470:
            Explosion(self, self.explosion_group)
            self.kill()


class PowerUp(pg.sprite.Sprite):
    speed = 4
    types = ["shield", "double", "life", "slow"]

    def __init__(self, *groups):
        pg.sprite.Sprite.__init__(self, *groups)

        self.type = random.choice(self.types)
        self.image = pg.Surface((26, 26))
        self.image.fill("black")

        if self.type == "shield":
            color = "cyan"
        elif self.type == "double":
            color = "yellow"
        elif self.type == "life":
            color = "green"
        else:
            color = "purple"

        pg.draw.circle(self.image, color, (13, 13), 12)
        self.image.set_colorkey("black")

        self.rect = self.image.get_rect()
        self.rect.centerx = random.randint(40, SCREENRECT.width - 40)
        self.rect.top = 0

    def update(self):
        self.rect.move_ip(0, self.speed)

        if self.rect.top > SCREENRECT.height:
            self.kill()


class Score(pg.sprite.Sprite):
    def __init__(self, *groups):
        pg.sprite.Sprite.__init__(self, *groups)
        self.font = pg.font.Font(None, 24)
        self.color = "white"
        self.lastscore = -1
        self.lastlives = -1
        self.update()
        self.rect = self.image.get_rect().move(10, 450)

    def update(self):
        global SCORE, LIVES

        if SCORE != self.lastscore or LIVES != self.lastlives:
            self.lastscore = SCORE
            self.lastlives = LIVES
            msg = f"Score: {SCORE}   Lives: {LIVES}"
            self.image = self.font.render(msg, True, self.color)


# -----------------------------
# AFFICHAGE TEXTE
# -----------------------------
def draw_text(screen, text, size, color, x, y, center=True):
    font = pg.font.Font(None, size)
    image = font.render(text, True, color)
    rect = image.get_rect()

    if center:
        rect.center = (x, y)
    else:
        rect.topleft = (x, y)

    screen.blit(image, rect)


# -----------------------------
# MENU PRINCIPAL
# -----------------------------
def main_menu(screen):
    global current_difficulty

    options = [
        "Commencer une nouvelle partie",
        "Voir les meilleurs scores",
        "Choisir le niveau de difficulté",
        "Quitter le jeu",
    ]

    selected = 0
    clock = pg.time.Clock()

    while True:
        screen.fill((10, 10, 30))

        draw_text(screen, "PYGAME ALIENS", 56, "white", 320, 70)
        draw_text(screen, f"Difficulté actuelle : {current_difficulty}", 28, "cyan", 320, 125)

        for i, option in enumerate(options):
            color = "yellow" if i == selected else "white"
            draw_text(screen, option, 32, color, 320, 200 + i * 50)

        draw_text(screen, "Flèches ↑ ↓ pour naviguer | ENTER pour choisir", 22, "gray", 320, 430)

        pg.display.flip()

        for event in pg.event.get():
            if event.type == pg.QUIT:
                return "quit"

            if event.type == pg.KEYDOWN:
                if event.key == pg.K_UP:
                    selected = (selected - 1) % len(options)

                elif event.key == pg.K_DOWN:
                    selected = (selected + 1) % len(options)

                elif event.key == pg.K_RETURN:
                    if selected == 0:
                        return "play"
                    elif selected == 1:
                        show_high_scores(screen)
                    elif selected == 2:
                        choose_difficulty(screen)
                    elif selected == 3:
                        return "quit"

        clock.tick(40)


def choose_difficulty(screen):
    global current_difficulty

    difficulties = list(DIFFICULTIES.keys())
    selected = difficulties.index(current_difficulty)
    clock = pg.time.Clock()

    while True:
        screen.fill((20, 20, 40))

        draw_text(screen, "CHOISIR LA DIFFICULTÉ", 44, "white", 320, 80)

        for i, diff in enumerate(difficulties):
            color = "yellow" if i == selected else "white"
            draw_text(screen, diff, 36, color, 320, 180 + i * 60)

        draw_text(screen, "ENTER pour confirmer | ESC pour revenir", 24, "gray", 320, 420)

        pg.display.flip()

        for event in pg.event.get():
            if event.type == pg.QUIT:
                pg.quit()
                raise SystemExit

            if event.type == pg.KEYDOWN:
                if event.key == pg.K_UP:
                    selected = (selected - 1) % len(difficulties)

                elif event.key == pg.K_DOWN:
                    selected = (selected + 1) % len(difficulties)

                elif event.key == pg.K_RETURN:
                    current_difficulty = difficulties[selected]
                    return

                elif event.key == pg.K_ESCAPE:
                    return

        clock.tick(40)


def show_high_scores(screen):
    scores = load_high_scores()
    clock = pg.time.Clock()

    while True:
        screen.fill((10, 10, 30))

        draw_text(screen, "MEILLEURS SCORES", 46, "white", 320, 70)

        if not scores:
            draw_text(screen, "Aucun score enregistré.", 30, "gray", 320, 200)
        else:
            for i, item in enumerate(scores):
                text = f"{i + 1}. {item['name']} - {item['score']} pts - {item['difficulty']}"
                draw_text(screen, text, 28, "yellow", 320, 150 + i * 45)

        draw_text(screen, "Appuie sur ESC pour revenir au menu", 24, "gray", 320, 430)

        pg.display.flip()

        for event in pg.event.get():
            if event.type == pg.QUIT:
                pg.quit()
                raise SystemExit

            if event.type == pg.KEYDOWN and event.key == pg.K_ESCAPE:
                return

        clock.tick(40)


def game_over_screen(screen):
    global SCORE

    save_high_score(SCORE, current_difficulty)

    clock = pg.time.Clock()

    while True:
        screen.fill((20, 0, 0))

        draw_text(screen, "GAME OVER", 60, "red", 320, 120)
        draw_text(screen, f"Score final : {SCORE}", 38, "white", 320, 210)
        draw_text(screen, "ENTER pour retourner au menu", 28, "yellow", 320, 310)

        pg.display.flip()

        for event in pg.event.get():
            if event.type == pg.QUIT:
                pg.quit()
                raise SystemExit

            if event.type == pg.KEYDOWN and event.key == pg.K_RETURN:
                return

        clock.tick(40)


# -----------------------------
# JEU PRINCIPAL
# -----------------------------
def run_game(screen, winstyle=0, bestdepth=32):
    global SCORE, LIVES

    SCORE = 0
    LIVES = 3

    settings = DIFFICULTIES[current_difficulty]

    fullscreen = False

    img = load_image("player1.gif")
    Player.images = [img, pg.transform.flip(img, 1, 0)]

    img = load_image("explosion1.gif")
    Explosion.images = [img, pg.transform.flip(img, 1, 1)]

    Alien.images = [load_image(im) for im in ("alien1.gif", "alien2.gif", "alien3.gif")]
    Bomb.images = [load_image("bomb.gif")]
    Shot.images = [load_image("shot.gif")]

    icon = pg.transform.scale(Alien.images[0], (32, 32))
    pg.display.set_icon(icon)
    pg.display.set_caption("Pygame Aliens")
    pg.mouse.set_visible(0)

    bgdtile = load_image("background.gif")
    background = pg.Surface(SCREENRECT.size)

    for x in range(0, SCREENRECT.width, bgdtile.get_width()):
        background.blit(bgdtile, (x, 0))

    screen.blit(background, (0, 0))
    pg.display.flip()

    boom_sound = load_sound("boom.wav")
    shoot_sound = load_sound("car_door.wav")

    if pg.mixer:
        music = os.path.join(main_dir, "data", "house_lo.wav")
        pg.mixer.music.load(music)
        pg.mixer.music.play(-1)

    aliens = pg.sprite.Group()
    shots = pg.sprite.Group()
    bombs = pg.sprite.Group()
    powerups = pg.sprite.Group()
    all = pg.sprite.RenderUpdates()
    lastalien = pg.sprite.GroupSingle()

    alienreload = ALIEN_RELOAD
    clock = pg.time.Clock()

    player = Player(all)
    Alien(settings["alien_speed"], aliens, all, lastalien)

    if pg.font:
        all.add(Score(all))

    shield_timer = 0
    double_timer = 0
    slow_timer = 0
    powerup_timer = 0

    while player.alive():
        for event in pg.event.get():
            if event.type == pg.QUIT:
                return "quit"

            if event.type == pg.KEYDOWN and event.key == pg.K_ESCAPE:
                return "menu"

            elif event.type == pg.KEYDOWN and event.key == pg.K_f:
                if not fullscreen:
                    screen_backup = screen.copy()
                    screen = pg.display.set_mode(
                        SCREENRECT.size,
                        winstyle | pg.FULLSCREEN,
                        bestdepth
                    )
                    screen.blit(screen_backup, (0, 0))
                else:
                    screen_backup = screen.copy()
                    screen = pg.display.set_mode(
                        SCREENRECT.size,
                        winstyle,
                        bestdepth
                    )
                    screen.blit(screen_backup, (0, 0))

                pg.display.flip()
                fullscreen = not fullscreen

        keystate = pg.key.get_pressed()

        all.clear(screen, background)
        all.update()

        # Timers des power-ups
        if shield_timer > 0:
            shield_timer -= 1
            player.shield = True
        else:
            player.shield = False

        if double_timer > 0:
            double_timer -= 1
            player.double_shot = True
        else:
            player.double_shot = False

        if slow_timer > 0:
            slow_timer -= 1
            alien_speed = max(3, settings["alien_speed"] // 2)
        else:
            alien_speed = settings["alien_speed"]

        # Mouvement du joueur
        direction = keystate[pg.K_RIGHT] - keystate[pg.K_LEFT]
        player.move(direction)

        # Tir du joueur
        firing = keystate[pg.K_SPACE]

        if not player.reloading and firing and len(shots) < MAX_SHOTS:
            if player.double_shot:
                Shot((player.rect.centerx - 12, player.rect.top), shots, all)
                Shot((player.rect.centerx + 12, player.rect.top), shots, all)
            else:
                Shot(player.gunpos(), shots, all)

            if pg.mixer and shoot_sound is not None:
                shoot_sound.play()

        player.reloading = firing

        # Création des aliens
        if alienreload:
            alienreload -= 1
        elif len(aliens) < settings["max_aliens"] and not int(random.random() * settings["alien_odds"]):
            Alien(alien_speed, aliens, all, lastalien)
            alienreload = ALIEN_RELOAD

        # Bombes ennemies
        if lastalien and not int(random.random() * settings["bomb_odds"]):
            Bomb(lastalien.sprite, all, bombs, all)

        # Apparition des power-ups
        powerup_timer += 1

        if powerup_timer > 350:
            if random.randint(1, 100) <= 35:
                PowerUp(powerups, all)
            powerup_timer = 0

        # Collision joueur / power-up
        for powerup in pg.sprite.spritecollide(player, powerups, True):
            if powerup.type == "shield":
                shield_timer = 300
            elif powerup.type == "double":
                double_timer = 300
            elif powerup.type == "life":
                LIVES += 1
            elif powerup.type == "slow":
                slow_timer = 300

        # Collision alien / joueur
        for alien in pg.sprite.spritecollide(player, aliens, True):
            if pg.mixer and boom_sound is not None:
                boom_sound.play()

            Explosion(alien, all)

            if player.shield:
                shield_timer = 0
            else:
                LIVES -= 1
                Explosion(player, all)

                if LIVES <= 0:
                    player.kill()

        # Collision tir / alien
        for alien in pg.sprite.groupcollide(aliens, shots, True, True).keys():
            if pg.mixer and boom_sound is not None:
                boom_sound.play()

            Explosion(alien, all)
            SCORE += 1

        # Collision bombe / joueur
        for bomb in pg.sprite.spritecollide(player, bombs, True):
            if pg.mixer and boom_sound is not None:
                boom_sound.play()

            Explosion(bomb, all)

            if player.shield:
                shield_timer = 0
            else:
                LIVES -= 1
                Explosion(player, all)

                if LIVES <= 0:
                    player.kill()

        # Affichage des effets actifs
        if player.shield:
            draw_text(screen, "BOUCLIER", 22, "cyan", 560, 20)

        if player.double_shot:
            draw_text(screen, "DOUBLE TIR", 22, "yellow", 550, 45)

        if slow_timer > 0:
            draw_text(screen, "RALENTI", 22, "purple", 560, 70)

        dirty = all.draw(screen)
        pg.display.update(dirty)
        clock.tick(40)

    if pg.mixer:
        pg.mixer.music.fadeout(1000)

    pg.time.wait(1000)
    return "game_over"


# -----------------------------
# PROGRAMME PRINCIPAL
# -----------------------------
def main():
    if pg.get_sdl_version()[0] == 2:
        pg.mixer.pre_init(44100, 32, 2, 1024)

    pg.init()

    if pg.mixer and not pg.mixer.get_init():
        print("Warning, no sound")
        pg.mixer = None

    winstyle = 0
    bestdepth = pg.display.mode_ok(SCREENRECT.size, winstyle, 32)
    screen = pg.display.set_mode(SCREENRECT.size, winstyle, bestdepth)

    while True:
        choice = main_menu(screen)

        if choice == "play":
            result = run_game(screen, winstyle, bestdepth)

            if result == "game_over":
                game_over_screen(screen)

            elif result == "quit":
                break

        elif choice == "quit":
            break

    pg.quit()


if __name__ == "__main__":
    main()

"""pygame-ce 2.5.7 (SDL 2.32.10, Python 3.14.4)
Traceback (most recent call last):
  File "/Users/giannisgambato/Documents/Aliens.py Test 2.py", line 707, in <module>
    main()
  File "/Users/giannisgambato/Documents/Aliens.py Test 2.py", line 692, in main
    result = run_game(screen, winstyle, bestdepth)
  File "/Users/giannisgambato/Documents/Aliens.py Test 2.py", line 455, in run_game
    img = load_image("player1.gif")
  File "/Users/giannisgambato/Documents/Aliens.py Test 2.py", line 53, in load_image
    surface = pg.image.load(file)
FileNotFoundError: No such file or directory: '/Users/giannisgambato/Documents/data/player1.gif'.

"""